name: UserSetting
version: '1.0-SNAPSHOT'
main: org.ide.userSetting.UserSetting
api-version: '1.20'

commands:
  hud:
    description: HUD 상태를 전환합니다.
    usage: /hud
  hudtoggle:
    description: Toggle HUD on or off
    usage: /hudtoggle
    permission: hudtoggle.use
    permission-message: You don't have permission to use this command.